version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow: "all"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow: "all"
