tasks:
  - init: mvn -U clean install site
gitConfig:
  alias.st: status
  core.autocrlf: input
  pull.rebase: "false"
vscode:
  extensions:
    - redhat.java
    - redhat.vscode-xml
    - SonarSource.sonarlint-vscode
    - eamodio.gitlens
